[profile.default]
src = "src"
out = "out"
test = "test"
cache_path = "cache_forge"
optimizer = true
optimizer_runs = 10_000
libs = ["node_modules", "lib"]
evm_version = "shanghai" 
solc = "0.8.26" 

[fmt]
bracket_spacing = true
int_types = "long"
line_length = 120
multiline_func_header = "all"
number_underscore = "thousands"
quote_style = "double"
tab_width = 4
wrap_comments = true

[rpc_endpoints]
mainnet = "https://eth-mainnet.g.alchemy.com/v2/ZTIF1v1YGwGePEvVO-qyfnmLL5t0N3KG"
sepolia = "https://sepolia.infura.io/v3/d670ac7f22c94d45a4a8729e2daf865a"

[etherscan]
mainnet = { key = "${ETHERSCAN_API_KEY}" }
sepolia = { key = "${ETHERSCAN_API_KEY}" }
